### ISSUE TITLE
Compiling problem (make - make install)

### ISSUE THREAD

**Issue by dpech** [alchemy-fr/Phraseanet-Indexer#3]
Hello,

I have try to compile the extension and have this error.
I have laucnh all the command

aclocal
automake -a
autoconf
./configure

but i have a probleme with make at the end 

g++  -g -O2   -o phraseanet_indexer main.o callback_record.o connbas.o connbas_abox.o connbas_dbox.o dom.o indexer.o lownodiacritics_utf8.o phrasea_clock_t.o sbas.o thesaurus.o trace_memory.o sockets.o syslog_xnix.o  -lpthread -lexpat -lxml2 -lmysqlclient
if test -n ""; \
        then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \
        fi;

and with make install (logical)

if test -n ""; \
        then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \
        fi;
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â»
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c phraseanet_indexer '/usr/local/bin'
make[1]: Rien Ã  faire pour Â« install-data-am Â».
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â»

Thank you very much for your help

**Comment by jygaulier** [comment]
Hello 
Those last 3 lines are NOT an error message (it's a library/path fix for OS-X platform which "should" do nothing on Linux). 
We will check on "precise" if something goes wrong. 

Anyway on Linux you can safely remove the last 4 lines 

all-local: 
if test -n "$(OSXMYSQLLIBDIR)"; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` $(OSXMYSQLLIBDIR)/libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

into the "Makefile.am" file, and run the build from the begining (you can run 'make -clean' before that to remove temp files). 

After 'make', do you get an executable "phraseanet_indexer" into the directory ? 

Hope this helps 

JY Gaulier, ALCHEMY 

----- Mail original -----

De: "dpech" reply@reply.github.com 
À: "jygaulier" gaulier@alchemy.fr 
Envoyé: Mardi 5 Juin 2012 09:48:06 
Objet: [Phraseanet-Indexer] Compiling problem (make - make install) (#3) 

Hello, 

I have try to compile the extension and have this error. 
I have laucnh all the command 

aclocal 
automake -a 
autoconf 
./configure 

but i have a probleme with make at the end 

g++ -g -O2 -o phraseanet_indexer main.o callback_record.o connbas.o connbas_abox.o connbas_dbox.o dom.o indexer.o lownodiacritics_utf8.o phrasea_clock_t.o sbas.o thesaurus.o trace_memory.o sockets.o syslog_xnix.o -lpthread -lexpat -lxml2 -lmysqlclient 
if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

and with make install (logical) 

if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin" 
/usr/bin/install -c phraseanet_indexer '/usr/local/bin' 
make[1]: Rien Ã faire pour Â« install-data-am Â». 
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 

Thank you very much for your help 

---

Reply to this email directly or view it on GitHub: 
https://github.com/alchemy-fr/Phraseanet-Indexer/issues/3

**Comment by dpech** [comment]
Hello,

Thank you for your quickly response.
I have delete the 4 lines in Makefile.am and run make : There is no message !
I can see "phraseanet_indexer" into the directory 

:/tmp/phraseanet_indexer# ls
aclocal.m4         config.log     connbas_abox.o  indexer.o               Makefile     phrasea_clock_t.o   sbas.o     syslog_xnix.o   WIN32
autom4te.cache     config.status  connbas_dbox.o  install-sh              Makefile.am  phraseanet_indexer  simpleopt  thesaurus.o     xNIX
callback_record.o  configure      connbas.o       lownodiacritics_utf8.o  Makefile.in  README.md           sockets.o  todo.txt
changelog.txt      configure.ac   dom.o           main.o                  missing      sample_args.txt     src        trace_memory.o

but after a "make install", i have

/tmp/phraseanet_indexer# make install
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â»
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c phraseanet_indexer '/usr/local/bin'
make[1]: Rien Ã  faire pour Â« install-data-am Â».
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â»

Thank you

----- Mail original -----
De: "jygaulier" reply@reply.github.com
À: "dpech" davy.pech@insa-rennes.fr
Envoyé: Mardi 5 Juin 2012 11:17:20
Objet: Re: [Phraseanet-Indexer] Compiling problem (make - make install) (#3)

Hello 
Those last 3 lines are NOT an error message (it's a library/path fix for OS-X platform which "should" do nothing on Linux). 
We will check on "precise" if something goes wrong. 

Anyway on Linux you can safely remove the last 4 lines 

all-local: 
if test -n "$(OSXMYSQLLIBDIR)"; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` $(OSXMYSQLLIBDIR)/libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

into the "Makefile.am" file, and run the build from the begining (you can run 'make -clean' before that to remove temp files). 

After 'make', do you get an executable "phraseanet_indexer" into the directory ? 

Hope this helps 

JY Gaulier, ALCHEMY 

----- Mail original -----

De: "dpech" reply@reply.github.com 
À: "jygaulier" gaulier@alchemy.fr 
Envoyé: Mardi 5 Juin 2012 09:48:06 
Objet: [Phraseanet-Indexer] Compiling problem (make - make install) (#3) 

Hello, 

I have try to compile the extension and have this error. 
I have laucnh all the command 

aclocal 
automake -a 
autoconf 
./configure 

but i have a probleme with make at the end 

g++ -g -O2 -o phraseanet_indexer main.o callback_record.o connbas.o connbas_abox.o connbas_dbox.o dom.o indexer.o lownodiacritics_utf8.o phrasea_clock_t.o sbas.o thesaurus.o trace_memory.o sockets.o syslog_xnix.o -lpthread -lexpat -lxml2 -lmysqlclient 
if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

and with make install (logical) 

if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin" 
/usr/bin/install -c phraseanet_indexer '/usr/local/bin' 
make[1]: Rien Ã faire pour Â« install-data-am Â». 
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 

Thank you very much for your help 

---

Reply to this email directly or view it on GitHub: 
https://github.com/alchemy-fr/Phraseanet-Indexer/issues/3

---

Reply to this email directly or view it on GitHub:
https://github.com/alchemy-fr/Phraseanet-Indexer/issues/3#issuecomment-6121089

## 

Davy PECH 
02.23.23.85.13 
Administrateur Système 
CRI (Centre de Ressources Informatiques) 
INSA de Rennes

**Comment by jygaulier** [comment]
Hello again, 
Again this is not a error message, it simply says the there is no 'data' to install. 
Here is the result on my debian : 

/workspace/Phraseanet-Indexer$ ls /usr/local/bin/phraseanet_indexer 
ls: impossible d'accéder à /usr/local/bin/phraseanet_indexer : Aucun fichier ou dossier de ce type 
/workspace/Phraseanet-Indexer$ sudo make instal l 
make[1]: entrant dans le répertoire « /home/gaulier/workspace/Phraseanet-Indexer » 
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin" 
/usr/bin/install -c phraseanet_indexer '/usr/local/bin' 
make[1]: Rien à faire pour « install-data-am ». 
make[1]: quittant le répertoire « /workspace/Phraseanet-Indexer » 
/workspace/Phraseanet-Indexer$ ls /usr/local/bin/phraseanet_indexer 
/usr/local/bin/phraseanet_indexer 

So after install you should be able to run "phraseanet_indexer -v". 
If not, check if the file has been copied to "/usr/local/bin", and check the 0755 mode. 
"phraseane_indexer" is a standalone file, so to install you can simply copy it anywhere on path (/usr/bin, /usr/local/bin...) 

Anyway, i f anything is wrong during make install, please let us know. 

btw... your system seems to be in french... alors on peut peut-être s'écrire en Français ? 

JY Gaulier, ALCHEMY 

----- Mail original -----

De: "dpech" reply@reply.github.com 
À: "jygaulier" gaulier@alchemy.fr 
Envoyé: Mardi 5 Juin 2012 11:23:56 
Objet: Re: [Phraseanet-Indexer] Compiling problem (make - make install) (#3) 

Hello, 

Thank you for your quickly response. 
I have delete the 4 lines in Makefile.am and run make : There is no message ! 
I can see "phraseanet_indexer" into the directory 

:/tmp/phraseanet_indexer# ls 
aclocal.m4 config.log connbas_abox.o indexer.o Makefile phrasea_clock_t.o sbas.o syslog_xnix.o WIN32 
autom4te.cache config.status connbas_dbox.o install-sh Makefile.am phraseanet_indexer simpleopt thesaurus.o xNIX 
callback_record.o configure connbas.o lownodiacritics_utf8.o Makefile.in README.md sockets.o todo.txt 
changelog.txt configure.ac dom.o main.o missing sample_args.txt src trace_memory.o 

but after a "make install", i have 

/tmp/phraseanet_indexer# make install 
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin" 
/usr/bin/install -c phraseanet_indexer '/usr/local/bin' 
make[1]: Rien Ã faire pour Â« install-data-am Â». 
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 

Thank you 

----- Mail original ----- 
De: "jygaulier" reply@reply.github.com 
À: "dpech" davy.pech@insa-rennes.fr 
Envoyé: Mardi 5 Juin 2012 11:17:20 
Objet: Re: [Phraseanet-Indexer] Compiling problem (make - make install) (#3) 

Hello 
Those last 3 lines are NOT an error message (it's a library/path fix for OS-X platform which "should" do nothing on Linux). 
We will check on "precise" if something goes wrong. 

Anyway on Linux you can safely remove the last 4 lines 

all-local: 
if test -n "$(OSXMYSQLLIBDIR)"; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` $(OSXMYSQLLIBDIR)/libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

into the "Makefile.am" file, and run the build from the begining (you can run 'make -clean' before that to remove temp files). 

After 'make', do you get an executable "phraseanet_indexer" into the directory ? 

Hope this helps 

JY Gaulier, ALCHEMY 

----- Mail original ----- 

De: "dpech" reply@reply.github.com 
À: "jygaulier" gaulier@alchemy.fr 
Envoyé: Mardi 5 Juin 2012 09:48:06 
Objet: [Phraseanet-Indexer] Compiling problem (make - make install) (#3) 

Hello, 

I have try to compile the extension and have this error. 
I have laucnh all the command 

aclocal 
automake -a 
autoconf 
./configure 

but i have a probleme with make at the end 

g++ -g -O2 -o phraseanet_indexer main.o callback_record.o connbas.o connbas_abox.o connbas_dbox.o dom.o indexer.o lownodiacritics_utf8.o phrasea_clock_t.o sbas.o thesaurus.o trace_memory.o sockets.o syslog_xnix.o -lpthread -lexpat -lxml2 -lmysqlclient 
if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 

and with make install (logical) 

if test -n ""; \ 
then install_name_tool -change `otool -L ./phraseanet_indexer |cut -f1 -d" "|grep libmysql` /libmysqlclient.dylib ./phraseanet_indexer; \ 
fi; 
make[1]: entrant dans le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin" 
/usr/bin/install -c phraseanet_indexer '/usr/local/bin' 
make[1]: Rien Ã faire pour Â« install-data-am Â». 
make[1]: quittant le rÃ©pertoire Â« /tmp/phraseanet_indexer Â» 

Thank you very much for your help 

---

Reply to this email directly or view it on GitHub: 
https://github.com/alchemy-fr/Phraseanet-Indexer/issues/3 

---

Reply to this email directly or view it on GitHub: 
https://github.com/alchemy-fr/Phraseanet-Indexer/issues/3#issuecomment-6121089 

## 

Davy PECH 
02.23.23.85.13 
Administrateur Système 
CRI (Centre de Ressources Informatiques) 
INSA de Rennes 

---

**Comment by dpech** [comment]
:-))))
Bonjour,

C'est Ok ! Merci pour les informations.
Je continue l'installation de Phraseanet.
Merci
Bonne journée
